# network: {config: disabled}
network:
  version: 2
  renderer: networkd

  ethernets:
    ens15f0:
      dhcp4: true
    ens15f1:
      dhcp4: false
    ens15f2:
      dhcp4: false
    ens15f3:
      dhcp4: true

  bridges:
    br12:
      interfaces: [ens15f1]
      addresses: [12.12.0.2/16]
      # gateway4 is deprecated, use routes instead
      routes:
      - to: default
        via: 12.12.0.1
        metric: 100
        on-link: true
      mtu: 1500
      nameservers:
        addresses: [8.8.8.8]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no
    br-real:
      interfaces: [ens15f2]
      addresses: [103.108.62.218/29]
      # gateway4 is deprecated, use routes instead
      routes:
      - to: default
        via: 103.108.62.217
        metric: 100
        on-link: true
      mtu: 1500
      nameservers:
        addresses: [8.8.8.8]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no

    br10:
      interfaces: [vlan10]
      addresses: [11.11.0.1/18]
      parameters:
        stp: false
        forward-delay: 0

    br20:
      interfaces: [vlan20]
      addresses: [11.11.64.1/18]
      parameters:
        stp: false
        forward-delay: 0

    br30:
      interfaces: [vlan30]
      addresses: [11.11.128.1/18]
      parameters:
        stp: false
        forward-delay: 0

    br40:
      interfaces: [vlan40]
      addresses: [11.11.192.1/18]
      parameters:
        stp: false
        forward-delay: 0




  vlans:
    vlan10:
      id: 10
      link: ens15f0
      addresses: [11.11.0.1/18]
    vlan20:
      id: 20
      link: ens15f0
      addresses: [11.11.64.1/18]
    vlan30:
      id: 30
      link: ens15f0
      addresses: [11.11.128.1/18]
    vlan40:
      id: 40
      link: ens15f0
      addresses: [11.11.192.1/18]
